language: generic

os: osx
osx_image: xcode6.4

before_install:
  - wget -O "$(brew --prefix)/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/ncar-ncl.rb" https://raw.githubusercontent.com/khallock/homebrew-cask/fix_ncar-ncl/Casks/ncar-ncl.rb
  - brew cask install ncar-ncl

script:
  - ncl -V
